### ISSUE TITLE
As a router, I should check that all of my subgraph clients are working on boot

### ISSUE THREAD

**Issue by jakekidd** [connext/monorepo#1499]
**Describe the bug**
Given a subgraph client that is set up incorrectly or points to wrong url, etc., we might see this error:
```
Mesh GraphQLError: deployment `connext/nxtp` does not exist
```

This error can occur during the `pollSubgraph` loop if the GraphQLError occurs:
```
{"level":"ERROR","time":1657670976437,"pid":1,"hostname":"a590636c29a4","name":"0x627306090abaB3A6e1400e9345bC60c78a8BEf57","requestContext":{"id":"tIskD1cTQ+SmfP/GbUZEhA/1494","origin":"pollSubgraph"},"methodContext":{"id":"tIskD1cTQ+SmfP/GbUZEhA/1493","name":"pollSubgraph"},"error":{"message":"Cannot read property 'block' of null","type":"TypeError","context":{},"stack":"TypeError: Cannot read property 'block' of null\n    at SubgraphReader.getLatestBlockNumber (/home/node/packages/adapters/subgraph/dist/src/reader.js:49:61)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async pollSubgraph (/home/node/packages/agents/router/dist/bindings/subgraph/index.js:40:36)\n    at async /home/node/packages/agents/router/dist/bindings/subgraph/index.js:22:17"},"msg":"Error getting pending txs, waiting for next loop"}
```

In general, we should probably be doing 1 test subgraph getBlockNumber query for each subgraph. We could do this on instantiation for SubgraphReader in the `adapters-subgraph` module. If a subgraph isn't responsive, we can mark that domain as "unsupported" and relay that information to whoever is instantiating the SubgraphReader (including router).

This sorting mechanism to get the supported chains is actually already being done, partially, in `SubgraphReader.create`! It's just not being used properly. See:
packages/adapters/subgraph/src/reader.ts
and
`setupSubgraphReader` in packages/agents/router/src/router.ts

This code already exists, it just isn't being used with the new graphql client stuff. Currently, **all** chains are being reported as "supported" according to SubgraphReader (no checks are performed).
```ts
  // Pull support for domains that don't have a subgraph.
  const supported: Record<string, boolean> = subgraphReader.supported;
  for (const domain of Object.keys(supported)) {
    // If the domain is set to false, it indicates the SubgraphReader did not find active subgraphs for that domain.
    if (!supported[domain]) {
      delete context.config.chains[domain];
    }
  }
  ```

**To Reproduce**
1. Run graph node
2. **Don't** deploy subgraph!
3. Run a router. You should see these errors listed above.

**Comment by jakekidd** [comment]
closing this out. according to current code here we are recording supported correctly:
https://github.com/connext/monorepo/blob/b78809770a1d4bd6b8e5cdbcf10688af909a6055/packages/adapters/subgraph/src/lib/helpers/create.ts#L47

Additionally it looks like we're throwing an error when domains' subgraphs are unsupported:
https://github.com/connext/monorepo/blob/b78809770a1d4bd6b8e5cdbcf10688af909a6055/packages/agents/router/src/setup.ts#L69
