### ISSUE TITLE
Optimism pool is broken 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3062]
**Describe the bug**
could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)

![image](https://user-images.githubusercontent.com/37959170/212434575-c3865810-7050-489f-bf77-09a48aec6396.png)

Terminal

Failed to load resource: net::ERR_CONNECTION_CLOSED
_app-e44f9b7fec30e000.js:1 Uncaught (in promise) Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x7F5c764cBc14f9669B88837ca1490cCa17c31607","data":"0x70a082310000000000000000000000006d91e35d502fb6f654992283e6e4f397fc23dc2c","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at y.makeError (_app-e44f9b7fec30e000.js:1:2396737)
    at y.throwError (_app-e44f9b7fec30e000.js:1:2396857)
    at _app-e44f9b7fec30e000.js:1:2445434
    at Array.forEach (<anonymous>)
    at k.<anonymous> (_app-e44f9b7fec30e000.js:1:2445249)
    at Generator.next (<anonymous>)
    at s (_app-e44f9b7fec30e000.js:1:2437716)

**Comment by alexwhte** [comment]
Error updated to this 
![image](https://user-images.githubusercontent.com/37959170/212434690-dbdfed95-6486-4932-9407-178f5c16b411.png)

**Comment by sanchaymittal** [comment]
<img width="1728" alt="Screenshot 2023-01-16 at 6 01 08 PM" src="https://user-images.githubusercontent.com/31698676/212678798-7ce5473a-0057-47db-adb5-12b54a4361b3.png">

Working for me, probably a network issue at that time. Or we did some fixes in the last couple of days.
