### ISSUE TITLE
As a SDK user, I want integrate stableswap subgraph in order to reduce rpc calls.

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/monorepo#3106]
## Problem
Stableswap subgraph provides balances and the virtual price of the pool.  SDK should use subgraph instead of calling the contract directly.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] integrate stable swap subgraph
- [ ] integrate multicall to sdk

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] X happens

**Comment by alexwhte** [comment]
Will this fix this RPC delay error?  It loaded after a while of waiting
![image](https://user-images.githubusercontent.com/37959170/214357775-d23a5afe-a685-4658-8fd7-d3f11450d5fa.png)
```
[getPool error] Object Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x5bB83e95f63217CDa6aE3D181BA580Ef377D2109","data":"0xf15376860000000000000000000000006a023ccd1ff6f2045c3309768ead9e68f978f6e1","accessList":null}, error={"reason":"missing response","code":"SERVER_ERROR","requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x5bb83e95f63217cda6ae3d181ba580ef377d2109\",\"data\":\"0xf15376860000000000000000000000006a023ccd1ff6f2045c3309768ead9e68f978f6e1\"},\"latest\"],\"id\":48,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","serverError":{},"url":"https://xdai-rpc.gateway.pokt.network"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at y.makeError (_app-60c740194e2fa78e.js:1:2398380)
    at y.throwError (_app-60c740194e2fa78e.js:1:2398500)
    at T (_app-60c740194e2fa78e.js:1:2478162)
    at d.<anonymous> (_app-60c740194e2fa78e.js:1:2488358)
    at Generator.throw (<anonymous>)
    at o (_app-60c740194e2fa78e.js:1:2477490)
```
