### ISSUE TITLE
Arbitrum showing no liquidity in Pool

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3117]
**To Reproduce**
1. Go to https://amarok.bridge.connext.network/USDC-from-ethereum-to-binance
2. Click on Pool tab
3. See below
![image](https://user-images.githubusercontent.com/37959170/213365428-b4c683f7-d573-43ca-83fa-213497d224f2.png)

NOTE: If i refresh it works, so not sure why this happens in this flow

**Comment by alexwhte** [comment]
```
[getUserPools error] {domain_id: '1634886255', address: '0x6d91e35d502fb6F654992283e6E4f397fC23DC2c'}address: "0x6d91e35d502fb6F654992283e6E4f397fC23DC2c"domain_id: "1634886255"[[Prototype]]: Object Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at y.makeError (_app-932120b0bcea2788.js:1:2396737)
    at y.throwError (_app-932120b0bcea2788.js:1:2396857)
    at d.<anonymous> (_app-932120b0bcea2788.js:1:2484071)
    at Generator.throw (<anonymous>)
    at o (_app-932120b0bcea2788.js:1:2475847)
```

**Comment by pjenviri** [comment]
Fixed it by changing RPC.
