### ISSUE TITLE
Mainnet Lighthouse Processer alerts review

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3167]
**Describe the bug**
We are getting better uptime alerts in here
https://discord.com/channels/992549151134982234/994129054347317248

![image](https://user-images.githubusercontent.com/37959170/213783112-659d31d8-1b80-4413-b062-dd6a2b5a7cc4.png)

**Comment by alexwhte** [comment]
![image](https://user-images.githubusercontent.com/37959170/213788104-ba3df91e-cc46-460e-a170-3220c878ff0d.png)

**Comment by preethamr** [comment]
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/1195648/213799420-2916bbe4-387b-4821-ab41-9c0ac0ef16bb.png">

Not seeing any DD logs for LH processor for the last 2 hours

**Comment by preethamr** [comment]
Reproduced it in local:
```
Error starting Prover. Sad! :( AxiosQueryError: Error sending axios request to url https://betteruptime.com/api/v1/heartbeat/oqtEd7uLJbDb6xUB1t8LPhRG
    at axiosPost (/Users/preetham/connext/repo/3167_main/monorepo/packages/utils/src/helpers/axios.ts:22:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at sendHeartbeat (/Users/preetham/connext/repo/3167_main/monorepo/packages/utils/src/helpers/health.ts:6:20)
    at makeProcessFromRoot (/Users/preetham/connext/repo/3167_main/monorepo/packages/agents/lighthouse/src/tasks/processFromRoot/processFromRoot.ts:83:7)
    at makeLighthouse (/Users/preetham/connext/repo/3167_main/monorepo/packages/agents/lighthouse/src/tasks/index.ts:27:7) {
  msg: 'Error sending axios request to url https://betteruptime.com/api/v1/heartbeat/oqtEd7uLJbDb6xUB1t8LPhRG',
  context: {
    url: 'https://betteruptime.com/api/v1/heartbeat/oqtEd7uLJbDb6xUB1t8LPhRG',
    data: undefined,
    method: 'post',
    error: { error: [Object], status: undefined }
  },
  type: 'AxiosQueryError',
  level: 'error',
  isNxtpError: true
}
```

**Comment by rhlsthrm** [comment]
So this means it's erroring sending to the health check URL?

**Comment by preethamr** [comment]
Yes.
This was an intermittent error

**Comment by preethamr** [comment]
Does not look like an issue with LH.
