### ISSUE TITLE
Lighthouse processFromRoot logging errors on staging

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3169]
**Describe the bug**
https://app.datadoghq.com/logs?query=service%3Alighthouse-process-from-root%20%40requestContext.transferId%3A0xf9c120ce382282a9757a323cc1dff4e6c36b780dab67ed5a853447c44d4c5edd&cols=service&event=AQAAAYXRY2A-wijpmQAAAABBWVhSWTJrN0FBREwtWFBicElqY0h3QVA&index=testnet-staging&messageDisplay=inline&saved-view-id=1433329&stream_sort=time%2Cdesc&viz=stream&from_ts=1674240306741&to_ts=1674254706741&live=true

```
Error: unable to find transaction receipt for 0xf9c120ce382282a9757a323cc1dff4e6c36b780dab67ed5a853447c44d4c5edd
    at CrossChainMessenger.getMessagesByTransaction (/var/task/node_modules/@eth-optimism/sdk/dist/cross-chain-messenger.js:237:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CrossChainMessenger.toCrossChainMessage (/var/task/node_modules/@eth-optimism/sdk/dist/cross-chain-messenger.js:334:30)
    at async CrossChainMessenger.getMessageStateRoot (/var/task/node_modules/@eth-optimism/sdk/dist/cross-chain-messenger.js:555:26)
    at async Object.getProcessFromOptimismRootArgs [as getArgs] (/var/task/packages/agents/lighthouse/dist/tasks/processFromRoot/helpers/optimism.js:27:18)
    at async processSingleRootMessage (/var/task/packages/agents/lighthouse/dist/tasks/processFromRoot/operations/processFromRoot.js:86:18)
    at async processFromRoot (/var/task/packages/agents/lighthouse/dist/tasks/processFromRoot/operations/processFromRoot.js:58:13)
    at async makeProcessFromRoot (/var/task/packages/agents/lighthouse/dist/tasks/processFromRoot/processFromRoot.js:65:9)
    at async makeLighthouse (/var/task/packages/agents/lighthouse/dist/tasks/index.js:29:13)
    at async handler (/var/task/packages/agents/lighthouse/dist/index.js:8:5)
```

**To Reproduce**
1. Go to Datadog
2. Look at staging logs for process from root

**Additional context**

**Comment by rhlsthrm** [comment]
Looks like these go away actually? Closing for now.
