### ISSUE TITLE
LH ProcessFromRoot should work [Staging] 

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4968]
## Summary
Ensure LH processFromRoot task works for all supported chains.

## Acceptance Criteria
- [ ] LH processFromRoot task works

**Comment by preethamr** [comment]
PFR fails here:
```
{
	"id": "AgAAAYsCJvQ-rHgcEgAAAAAAAAAYAAAAAEFZc0NKdldDQUFDWFFOOWttQm52NlFBSQAAACQAAAAAMDE4YjAyMjYtZmJmZC00ZTk2LTgwMTktMjVjNTM5NDgxODQx",
	"content": {
		"timestamp": "2023-10-05T23:23:09.246Z",
		"tags": [
			"account_id:679752396206",
			"functionname:lighthouse-process-from-root-testnet-staging",
			"function_arn:arn:aws:lambda:us-east-1:679752396206:function:lighthouse-process-from-root-testnet-staging",
			"env:testnet-staging",
			"source:lambda",
			"dd_extension_version:49",
			"region:us-east-1",
			"runtime:nodejs18.x",
			"aws_account:679752396206",
			"architecture:x86_64",
			"memorysize:512",
			"resource:lighthouse-process-from-root-testnet-staging",
			"service:lighthouse-process-from-root",
			"datadog.submission_auth:private_api_key"
		],
		"host": "169.254.214.73",
		"service": "lighthouse-process-from-root",
		"message": "Tx will be reverted with execution reverted: !length on chain, Skip other relayers",
		"attributes": {
			"stack": "Error: Transaction would fail on chain.\n    at parseError (/var/task/packages/adapters/txservice/dist/shared/errors.js:411:16)\n    at /var/task/packages/adapters/txservice/dist/shared/provider.js:105:67\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
			"level": "INFO",
			"methodContext": {
				"name": "sendWithRelayerWithBackup",
				"id": "sbKZ/36oToeAWfj3fNch3A/34"
			},
			"pid": 15,
			"type": "TransactionReverted",
			"hostname": "169.254.214.73",
			"lambda": {
				"arn": "arn:aws:lambda:us-east-1:679752396206:function:lighthouse-process-from-root-testnet-staging",
				"request_id": "671dd42e-8d5c-4129-9710-d333ff24124a"
			},
			"requestContext": {
				"origin": "processFromRoot",
				"id": "sbKZ/36oToeAWfj3fNch3A/31",
				"transferId": "0xd2163518a68f8a31f8c658b97cd97c1532084abcc2490b22ab14bd16231e607e"
			},
			"service": "lighthouse-process-from-root",
			"name": "lighthouse",
			"context": {
				"reason": "processing response error",
				"code": "SERVER_ERROR",
				"data": "0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000007216c656e67746800000000000000000000000000000000000000000000000000",
				"name": "n/a",
				"message": "execution reverted: !length"
			},
			"time": 1696548189209,
			"status": "info",
			"timestamp": 1696548189246
		}
	}
}
```

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/4981

Optimism connector fixed and processFromRoot works
