### ISSUE TITLE
Ensure LH propagate task works for all supported chains. [Staging] 

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4970]
## Summary
Ensure LH propagate task works for all supported chains.

## Acceptance Criteria
- [ ] LH propagate task works for all supported chains.

**Comment by preethamr** [comment]
In some cases we get this error:
```
{
	"id": "AgAAAYsCJvQ-rHgcEgAAAAAAAAAYAAAAAEFZc0NKdldDQUFDWFFOOWttQm52NlFBSQAAACQAAAAAMDE4YjAyMjYtZmJmZC00ZTk2LTgwMTktMjVjNTM5NDgxODQx",
	"content": {
		"timestamp": "2023-10-05T23:23:09.246Z",
		"tags": [
			"account_id:679752396206",
			"functionname:lighthouse-process-from-root-testnet-staging",
			"function_arn:arn:aws:lambda:us-east-1:679752396206:function:lighthouse-process-from-root-testnet-staging",
			"env:testnet-staging",
			"source:lambda",
			"dd_extension_version:49",
			"region:us-east-1",
			"runtime:nodejs18.x",
			"aws_account:679752396206",
			"architecture:x86_64",
			"memorysize:512",
			"resource:lighthouse-process-from-root-testnet-staging",
			"service:lighthouse-process-from-root",
			"datadog.submission_auth:private_api_key"
		],
		"host": "169.254.214.73",
		"service": "lighthouse-process-from-root",
		"message": "Tx will be reverted with execution reverted: !length on chain, Skip other relayers",
		"attributes": {
			"stack": "Error: Transaction would fail on chain.\n    at parseError (/var/task/packages/adapters/txservice/dist/shared/errors.js:411:16)\n    at /var/task/packages/adapters/txservice/dist/shared/provider.js:105:67\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
			"level": "INFO",
			"methodContext": {
				"name": "sendWithRelayerWithBackup",
				"id": "sbKZ/36oToeAWfj3fNch3A/34"
			},
			"pid": 15,
			"type": "TransactionReverted",
			"hostname": "169.254.214.73",
			"lambda": {
				"arn": "arn:aws:lambda:us-east-1:679752396206:function:lighthouse-process-from-root-testnet-staging",
				"request_id": "671dd42e-8d5c-4129-9710-d333ff24124a"
			},
			"requestContext": {
				"origin": "processFromRoot",
				"id": "sbKZ/36oToeAWfj3fNch3A/31",
				"transferId": "0xd2163518a68f8a31f8c658b97cd97c1532084abcc2490b22ab14bd16231e607e"
			},
			"service": "lighthouse-process-from-root",
			"name": "lighthouse",
			"context": {
				"reason": "processing response error",
				"code": "SERVER_ERROR",
				"data": "0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000007216c656e67746800000000000000000000000000000000000000000000000000",
				"name": "n/a",
				"message": "execution reverted: !length"
			},
			"time": 1696548189209,
			"status": "info",
			"timestamp": 1696548189246
		}
	}
}
```

**Comment by preethamr** [comment]
Execution context for the above ^
```
{
	"id": "AgAAAYsCF-zO8g0c2wAAAAAAAAAYAAAAAEFZc0NGLTNOQUFEOEVUYXdGeTlqQWdBTQAAACQAAAAAMDE4YjAyMWItNWQ3YS00ZTYwLThkOTMtM2JhODdlZjY0NTU1",
	"content": {
		"timestamp": "2023-10-05T23:06:44.302Z",
		"tags": [
			"account_id:679752396206",
			"function_arn:arn:aws:lambda:us-east-1:679752396206:function:lighthouse-propagate-testnet-staging",
			"service:lighthouse-propagate",
			"memorysize:2048",
			"functionname:lighthouse-propagate-testnet-staging",
			"env:testnet-staging",
			"source:lambda",
			"region:us-east-1",
			"dd_extension_version:49",
			"runtime:nodejs18.x",
			"architecture:x86_64",
			"aws_account:679752396206",
			"resource:lighthouse-propagate-testnet-staging",
			"datadog.submission_auth:private_api_key"
		],
		"host": "169.254.182.249",
		"service": "lighthouse-propagate",
		"message": "Getting gas estimate",
		"attributes": {
			"data": "0x9a2652db0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000001bb0bb3d25ec70968fc65684061d0f73d634c7a1000000000000000000000000565c74da2aa4842c2c53adaa22da93e060177a6400000000000000000000000089c317adb9d3d9453870ca37dcc704d539fc2ddb000000000000000000000000c08edcc02e7a085da3bbf87afbbcad21ebf9094400000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000650a69e2f5800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000088b8000000000000000000000000000000000000000000000000000000000000d0a340000000000000000000000000000000000000000000000000000000007bfa480000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
			"level": "DEBUG",
			"methodContext": {
				"name": "send",
				"id": "lARkGbdgRUunl7w3FAClcw/26"
			},
			"pid": 16,
			"hostname": "169.254.182.249",
			"lambda": {
				"arn": "arn:aws:lambda:us-east-1:679752396206:function:lighthouse-propagate-testnet-staging",
				"request_id": "526709a6-b9ac-4e72-be04-60e307cfad61"
			},
			"requestContext": {
				"origin": "propagate",
				"id": "lARkGbdgRUunl7w3FAClcw/22"
			},
			"chainId": 5,
			"service": "lighthouse-propagate",
			"name": "lighthouse",
			"from": "0x75bA5Af8EFFDCFca32E1e288806d54277D1fde99",
			"time": 1696547204296,
			"to": "0x65713824d38ed8C65acE1d5Ab41CF93506ffa8C3",
			"status": "info",
			"timestamp": 1696547204302
		}
	}
}
```

**Comment by liu-zhipeng** [comment]
Done!!
https://github.com/connext/monorepo/pull/5012
