### ISSUE TITLE
Ensure LH proveAndProcess task works for all supported chains. [Staging] 

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4971]
## Summary
Ensure LH proveAndProcess task works for all supported chains.

## Acceptance Criteria
- [ ] LH proveAndProcess task works for all supported chains.

**Comment by preethamr** [comment]
Processing message fails with :
```
{
	"id": "AgAAAYsCLDfouY0cIAAAAAAAAAAYAAAAAEFZc0NMRGlmQUFDWFFOOWttQ244X2dBVwAAACQAAAAAMDE4YjAyMmMtNTI4My00MDg3LTg2MzQtNzU3MWUyN2EwODBk",
	"content": {
		"timestamp": "2023-10-05T23:28:54.248Z",
		"tags": [
			"function_arn:arn:aws:lambda:us-east-1:679752396206:function:lighthouse-prover-testnet-staging",
			"account_id:679752396206",
			"memorysize:10240",
			"resource:lighthouse-prover-testnet-staging",
			"env:testnet-staging",
			"source:lambda",
			"dd_extension_version:49",
			"region:us-east-1",
			"runtime:nodejs18.x",
			"aws_account:679752396206",
			"architecture:x86_64",
			"service:lighthouse-prover",
			"functionname:lighthouse-prover-testnet-staging",
			"datadog.submission_auth:private_api_key"
		],
		"host": "169.254.22.61",
		"service": "lighthouse-prover",
		"message": "Error processing messages on origin",
		"attributes": {
			"destinationDomain": "1735356532",
			"level": "error",
			"methodContext": {
				"name": "enqueue",
				"id": "xOS0s7taRzaFkxsHx7DZJA/25"
			},
			"pid": 21,
			"error": {
				"stack": "Error: No count for Aggregated Root 0x3431a358e4be663e12bb54f41557e3dcc527de47eb42f1099e5408ecac4621c1 found.\n    at /var/task/packages/agents/lighthouse/dist/tasks/prover/operations/publisher.js:177:31\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at async /var/task/packages/agents/lighthouse/dist/tasks/prover/operations/publisher.js:119:13\n    at async Promise.all (index 3)\n    at async enqueue (/var/task/packages/agents/lighthouse/dist/tasks/prover/operations/publisher.js:109:5)\n    at async makeProverPublisher (/var/task/packages/agents/lighthouse/dist/tasks/prover/prover.js:27:9)\n    at async makeLighthouse (/var/task/packages/agents/lighthouse/dist/tasks/index.js:22:13)\n    at async handler (/var/task/packages/agents/lighthouse/dist/index.js:8:5)",
				"kind": "Error",
				"message": "No count for Aggregated Root 0x3431a358e4be663e12bb54f41557e3dcc527de47eb42f1099e5408ecac4621c1 found.",
				"type": "NoAggregateRootCount"
			},
			"originDomain": "1734439522",
			"hostname": "169.254.22.61",
			"lambda": {
				"arn": "arn:aws:lambda:us-east-1:679752396206:function:lighthouse-prover-testnet-staging",
				"request_id": "2db3f98e-5f22-4da2-aa1e-dbe80bb2cc26"
			},
			"requestContext": {
				"origin": "enqueue",
				"id": "xOS0s7taRzaFkxsHx7DZJA/26"
			},
			"service": "lighthouse-prover",
			"name": "lighthouse",
			"time": 1696548534248,
			"status": "info",
			"timestamp": 1696548534248
		}
	}
}
```

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/4992
