### ISSUE TITLE
LH Prover should domain removal/missing from finalized snapshot

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#5166]
**Describe the bug**

https://app.datadoghq.com/logs?query=region%3Aus-east-1%20status%3Aerror%20-service%3Awatcher&cols=host%2Cservice&event=AgAAAYvK2qIURKMDcQAAAAAAAAAYAAAAAEFZdksycVRHQUFEbzBlUFdyYlgxQUFBTQAAACQAAAAAMDE4YmNhZGUtODc1Ny00NGQwLWExNGMtMWNkMDY1Y2ZhYjUz&index=&messageDisplay=inline&refresh_mode=sliding&stream_sort=time%2Cdesc&viz=stream&from_ts=1670349483271&to_ts=1670363883271&live=true

**To Reproduce**
1. Go to '[...](https://app.datadoghq.com/logs?query=region%3Aus-east-1%20status%3Aerror%20-service%3Awatcher&cols=host%2Cservice&event=AgAAAYvK2qIURKMDcQAAAAAAAAAYAAAAAEFZdksycVRHQUFEbzBlUFdyYlgxQUFBTQAAACQAAAAAMDE4YmNhZGUtODc1Ny00NGQwLWExNGMtMWNkMDY1Y2ZhYjUz&index=&messageDisplay=inline&refresh_mode=sliding&stream_sort=time%2Cdesc&viz=stream&from_ts=1670349483271&to_ts=1670363883271&live=true)'

**Additional context**
```{
	"id": "AgAAAYvK2qIURKMDcQAAAAAAAAAYAAAAAEFZdksycVRHQUFEbzBlUFdyYlgxQUFBTQAAACQAAAAAMDE4YmNhZGUtODc1Ny00NGQwLWExNGMtMWNkMDY1Y2ZhYjUz",
	"content": {
		"timestamp": "2023-11-13T22:43:27.892Z",
		"tags": [
			"function_arn:arn:aws:lambda:us-east-1:679752396206:function:lighthouse-prover-testnet-staging",
			"account_id:679752396206",
			"resource:lighthouse-prover-testnet-staging",
			"runtime:image",
			"dd_extension_version:50",
			"env:testnet-staging",
			"source:lambda",
			"region:us-east-1",
			"architecture:x86_64",
			"aws_account:679752396206",
			"memorysize:512",
			"service:lighthouse-prover",
			"functionname:lighthouse-prover-testnet-staging",
			"datadog.submission_auth:private_api_key"
		],
		"host": "169.254.71.141",
		"service": "lighthouse-prover",
		"message": "Error processing messages on origin",
		"attributes": {
			"destinationDomain": "1735356532",
			"level": "error",
			"methodContext": {
				"name": "enqueue",
				"id": "HwagSJoESNajXwaNCvquyw/25"
			},
			"pid": 17,
			"error": {
				"stack": "Error: No domain 1734439522 found in snapshot [object Object]\n    at /var/task/packages/agents/lighthouse/dist/tasks/prover/operations/publisher.js:183:35\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at async /var/task/packages/agents/lighthouse/dist/tasks/prover/operations/publisher.js:111:13\n    at async Promise.all (index 3)\n    at async enqueue (/var/task/packages/agents/lighthouse/dist/tasks/prover/operations/publisher.js:109:5)\n    at async makeProverPublisher (/var/task/packages/agents/lighthouse/dist/tasks/prover/prover.js:27:9)\n    at async makeLighthouse (/var/task/packages/agents/lighthouse/dist/tasks/index.js:22:13)\n    at async handler (/var/task/packages/agents/lighthouse/dist/index.js:8:5)",
				"kind": "Error",
				"message": "No domain 1734439522 found in snapshot [object Object]",
				"type": "NoDomainInSnapshot"
			},
			"originDomain": "1734439522",
			"hostname": "169.254.71.141",
			"lambda": {
				"arn": "arn:aws:lambda:us-east-1:679752396206:function:lighthouse-prover-testnet-staging",
				"request_id": "1301ddac-f7d5-4b4f-9464-a7a5059d5a47"
			},
			"requestContext": {
				"origin": "enqueue",
				"id": "HwagSJoESNajXwaNCvquyw/26"
			},
			"service": "lighthouse-prover",
			"name": "lighthouse",
			"time": 1699915407836,
			"status": "info",
			"timestamp": 1699915407892
		}
	}
}```

**Comment by preethamr** [comment]
This is already handled, and is a not fatal error, that will resolve, when a snapshot with the missing domain is finalized, or when the domain missing domain is removed from LH config.
Wont fix.
