### ISSUE TITLE
Gnosis router not bidding

### ISSUE THREAD

**Issue by par94** [connext/monorepo#5920]
**Describe the bug**
Gnosis router not bidding

Logs:
No NXTP_CONFIG exists, using config file and individual env vars
Error starting router publisher. Sad! :( Error: No Connext contract address for domain 2053862243
    at /home/node/packages/agents/router/dist/config.js:237:31
    at /home/node/packages/agents/router/dist/config.js:240:19
    at Array.forEach (<anonymous>)
    at getEnvConfig (/home/node/packages/agents/router/dist/config.js:223:39)
    at getConfig (/home/node/packages/agents/router/dist/config.js:271:47)
    at makePublisher (/home/node/packages/agents/router/dist/tasks/publisher/publisher.js:29:75)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Link to ticket in discord**

**Additional context**
@oncall

**Comment by preethamr** [comment]
Notified Gnosis, the resolution:
https://discord.com/channels/454734546869551114/816703710859100211/1222232915405049929

**Comment by preethamr** [comment]
cc @par94
